// Generated by CoffeeScript 1.8.0
(function() {
  var accord, apply_sourcemap, gutil, map, path, rext;

  gutil = require('gulp-util');

  accord = require('accord');

  map = require('map-stream');

  path = require('path');

  apply_sourcemap = require('vinyl-sourcemaps-apply');

  rext = require('replace-ext');

  module.exports = function(lang, opts) {
    var PLUGIN_NAME, adapter, err;
    if (opts == null) {
      opts = {};
    }
    PLUGIN_NAME = 'gulp-accord';
    if (!accord.supports(lang)) {
      throw new Error("" + PLUGIN_NAME + ": Language '" + lang + "' not supported");
    }
    try {
      adapter = accord.load(lang, path.join(module.parent.paths[0], lang));
    } catch (_error) {
      err = _error;
      throw new Error("" + PLUGIN_NAME + ": " + lang + " not installed. Try 'npm i " + lang + " -S'");
    }
    return map(function(file, cb) {
      if (file.isNull()) {
        return cb();
      }
      if (file.isStream()) {
        return cb(new gutil.PluginError(PLUGIN_NAME, "streams not supported!"));
      }
      if (file.sourceMap) {
        opts.sourcemap = true;
      }
      if (!opts.filename) {
        opts.filename = file.path;
      }
      if (file.isBuffer()) {
        return adapter.render(String(file.contents), opts).then(function(res) {
          file.path = rext(file.path, "." + adapter.output);
          file.contents = new Buffer(res.result);
          if (res.sourcemap) {
            return apply_sourcemap(file, res.sourcemap);
          }
        }).done((function() {
          return cb(null, file);
        }), function(err) {
          gutil.log(err);
          return cb(new gutil.PluginError(PLUGIN_NAME, err));
        });
      }
    }, {
      failures: true
    });
  };

}).call(this);
